### 상품추가
POST http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiaThTYk9hYjFoMm1vbkNOVnpoejR5aHg3amh0Yzgvd3Q4YmdHWTc1R1VNPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzU0MTMwNzc5LCJleHAiOjE3NTQyMTcxNzl9.HDgEpffC_8xUKA7Cze4Oq84B-ljwreUGhNtwUZIFAeM

{
  "description": "상품 설명",
  "items": [
    {
      "count": 1,
      "name": "270",
      "price": 100000
    }
  ],
  "name": "나이키 에어포스"
}

### 상품 아이템 추가
POST http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiaThTYk9hYjFoMm1vbkNOVnpoejR5aHg3amh0Yzgvd3Q4YmdHWTc1R1VNPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzU0MTMwNzc5LCJleHAiOjE3NTQyMTcxNzl9.HDgEpffC_8xUKA7Cze4Oq84B-ljwreUGhNtwUZIFAeM


{
  "productId": 1,
  "count": 1,
  "name": "280",
  "price": 100000
}

### 상품 수정
PUT http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiaThTYk9hYjFoMm1vbkNOVnpoejR5aHg3amh0Yzgvd3Q4YmdHWTc1R1VNPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzU0MTMwNzc5LCJleHAiOjE3NTQyMTcxNzl9.HDgEpffC_8xUKA7Cze4Oq84B-ljwreUGhNtwUZIFAeM

{
  "description": "상품 설명",
  "items": [
    {
      "id": 1,
      "count": 1,
      "name": "280",
      "price": 100000
    }
  ],
  "id": 1,
  "name": "나이키 에어포스 한정판"
}

### 상품 아이템 수정
PUT http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiaThTYk9hYjFoMm1vbkNOVnpoejR5aHg3amh0Yzgvd3Q4YmdHWTc1R1VNPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzU0MTMwNzc5LCJleHAiOjE3NTQyMTcxNzl9.HDgEpffC_8xUKA7Cze4Oq84B-ljwreUGhNtwUZIFAeM

{
  "id": 1,
  "count": 1,
  "name": "260",
  "price": 100000
}


### 상품 삭제
DELETE http://localhost:8082/seller/product?id=1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiaThTYk9hYjFoMm1vbkNOVnpoejR5aHg3amh0Yzgvd3Q4YmdHWTc1R1VNPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzU0MTMwNzc5LCJleHAiOjE3NTQyMTcxNzl9.HDgEpffC_8xUKA7Cze4Oq84B-ljwreUGhNtwUZIFAeM

{
  "description": "상품 설명",
  "items": [
    {
      "id": 1,
      "count": 1,
      "name": "280",
      "price": 100000
    }
  ],
  "id": 1,
  "name": "나이키 에어포스 한정판"
}



### 상품 아이템 삭제
DELETE http://localhost:8082/seller/product/item?id=2
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiaThTYk9hYjFoMm1vbkNOVnpoejR5aHg3amh0Yzgvd3Q4YmdHWTc1R1VNPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzU0MTMwNzc5LCJleHAiOjE3NTQyMTcxNzl9.HDgEpffC_8xUKA7Cze4Oq84B-ljwreUGhNtwUZIFAeM


### 상품 검색
GET http://localhost:8082/search/product?name=나이키
Content-Type: application/json

### 상품 디테일 검색
GET http://localhost:8082/search/product/detail?productId=1
Content-Type: application/json


### 카트 추가
POST http://localhost:8082/customer/cart
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiaThTYk9hYjFoMm1vbkNOVnpoejR5aHg3amh0Yzgvd3Q4YmdHWTc1R1VNPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NTQwNTY5NDgsImV4cCI6MTc1NDE0MzM0OH0.dTlXe0GnzVD4zsaVdKKGR72z5qOHBmIvirXwQCrUPgU

{
  "description": "상품 설명",
  "id": 1,
  "items": [
    {
      "count": 1,
      "id": 1,
      "name": "270",
      "price": 100000
    }
  ],
  "name": "나이키 에어포스",
  "sellerId": 1
}

### 카트 조회
GET http://localhost:8082/customer/cart
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiaThTYk9hYjFoMm1vbkNOVnpoejR5aHg3amh0Yzgvd3Q4YmdHWTc1R1VNPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NTQwNTY5NDgsImV4cCI6MTc1NDE0MzM0OH0.dTlXe0GnzVD4zsaVdKKGR72z5qOHBmIvirXwQCrUPgU

### 카트 주문
POST http://localhost:8082/customer/cart/order
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiaThTYk9hYjFoMm1vbkNOVnpoejR5aHg3amh0Yzgvd3Q4YmdHWTc1R1VNPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NTQwNTY5NDgsImV4cCI6MTc1NDE0MzM0OH0.dTlXe0GnzVD4zsaVdKKGR72z5qOHBmIvirXwQCrUPgU

{
  "customerId": 1,
  "products": [
    {
      "id": 1,
      "sellerId": 1,
      "name": "나이키 에어포스",
      "description": "상품 설명",
      "items": [
        {
          "id": 1,
          "name": "270",
          "count": 1,
          "price": 100000
        }
      ]
    }
  ],
  "messages": []
}
